// src/lib/continuation/brief-schema.ts
//
// The five-section continuation brief — the canonical structured
// output of the brief generator (Opus). See section "The Continuation
// Brief" in docs/ROADMAP_CONTINUATION.md.

import { z } from 'zod';

/**
 * One fork in the continuation brief. The founder picks one and the
 * cycle generates the next-cycle roadmap from it. Forks are NOT a
 * passive menu — each one is a real decision with concrete first
 * action and an honest "right if" condition.
 */
export const ContinuationForkSchema = z.object({
  id: z.string().describe(
    'Stable id for the fork — "fork-1", "fork-2", "fork-3". Used by the founder pick API as the fork selector.'
  ),
  title: z.string().describe(
    'Short imperative phrase capturing the direction. Verb-first. Example: "Double down on catering customers" or "Build the founder community first".'
  ),
  rationale: z.string().describe(
    'Two sentences: why this fork is on the menu given what the founder learned from execution. Reference specific evidence — task titles, parking-lot items, blocker patterns.'
  ),
  firstStep: z.string().describe(
    'One concrete first task the founder could start tomorrow. Achievable in their actual hours per week, not their stated hours. Specific enough to be done in 2-4 hours.'
  ),
  timeEstimate: z.string().describe(
    'Realistic timeline for the first meaningful result on this fork, calibrated to the founder\'s ACTUAL execution speed (not their original stated hours). Reference the calibration explicitly when the actual pace differed from the stated pace.'
  ),
  rightIfCondition: z.string().describe(
    'One sentence: "This fork is right if [condition specific to the founder\'s actual situation]." Never generic — must reference something the founder learned by executing.'
  ),
});
export type ContinuationFork = z.infer<typeof ContinuationForkSchema>;

/**
 * One parking-lot item as it appears in the brief. Mirrors the
 * runtime ParkingLotItem shape minus the id (the brief renders by
 * value, not by reference). The agent does not need the id to render
 * the item — the founder reads them in order.
 */
export const ParkingLotBriefEntrySchema = z.object({
  idea:         z.string(),
  surfacedAt:   z.string(),
  surfacedFrom: z.string(),
  taskContext:  z.string().nullable(),
});
export type ParkingLotBriefEntry = z.infer<typeof ParkingLotBriefEntrySchema>;

/**
 * The five-section continuation brief. Generated by Opus from the
 * full execution evidence base — roadmap progress, check-in
 * transcripts, parking-lot items, execution metrics, and the original
 * recommendation context. Validated through this schema before write.
 */
export const ContinuationBriefSchema = z.object({
  whatHappened: z.string().describe(
    'Section 1 — 3 to 4 sentences interpreting what the founder learned by executing the roadmap. NOT a list of completed tasks — an interpretation. Reference specific tasks where relevant. The interpretation quality is the entire value of continuation.'
  ),
  whatIGotWrong: z.string().describe(
    'Section 2 — explicitly name where the original recommendation\'s assumptions, market hypotheses, or time estimates diverged from what actually happened. If nothing was wrong, say so honestly. If multiple things were wrong, name the most important one. This builds trust through intellectual honesty AND produces the most valuable training signal.'
  ),
  whatTheEvidenceSays: z.string().describe(
    'Section 3 — the strongest signal from check-in transcripts, blocker patterns, parking-lot items, and any feedback. Specific and interpretive. Quote the founder\'s own words back when relevant. NOT a metrics summary; an interpretation of what the metrics mean for the path ahead.'
  ),
  forks: z.array(ContinuationForkSchema).describe(
    'Section 4 — 2 to 3 forks. Each one is a real decision the founder can make. Not a menu to pick passively. Distinct directions, each with concrete first move and "right if" condition. The phase count of any next roadmap is implied by the fork shape, not by a default.'
  ),
  parkingLotItems: z.array(ParkingLotBriefEntrySchema).describe(
    'Section 5 — every parking-lot item from the roadmap, surfaced now because this is the moment they may be relevant. May be empty if no items were captured during execution. Do not invent items; pass through the items provided in the input verbatim.'
  ),
  closingThought: z.string().describe(
    '2 to 3 sentences addressed directly to the founder. Acknowledge what they did, frame the choice ahead, and end with "the next decision is yours". Honest, never patronising.'
  ),
});
export type ContinuationBrief = z.infer<typeof ContinuationBriefSchema>;

/**
 * Safely parse a Roadmap.continuationBrief JSONB value. Returns null
 * on parse failure (corrupt row, schema drift) so the caller can
 * surface "no brief yet" without a runtime crash.
 */
export function safeParseContinuationBrief(value: unknown): ContinuationBrief | null {
  if (value == null) return null;
  const parsed = ContinuationBriefSchema.safeParse(value);
  return parsed.success ? parsed.data : null;
}
