// src/inngest/functions/documentation-agent-function.ts
/**
 * Documentation Agent Inngest Function
 * Triggered to generate comprehensive project documentation
 */

import { inngest } from "../client";
import { documentationAgent } from "@/lib/agents/documentation/documentation-agent";
import prisma from "@/lib/prisma";
import { logger } from "@/lib/logger";

export const documentationAgentFunction = inngest.createFunction(
  {
    id: "documentation-agent-generation",
    name: "Documentation Agent - Generate Project Docs",
    retries: 2,
  },
  { event: "agent/documentation.generate" },
  async ({ event, step }) => {
    const { taskId, projectId, userId, conversationId, taskInput } = event.data;

    logger.info(`[Inngest] Documentation Agent triggered`, {
      taskId,
      projectId,
      includeUserGuide: taskInput?.includeUserGuide,
      includeAPIDocs: taskInput?.includeAPIDocs,
    });

    try {
      // Step 1: Get project context
      const projectContext = await step.run("get-project-context", async () => {
        return await prisma.projectContext.findUnique({
          where: { projectId },
          select: { techStack: true, architecture: true, codebase: true },
        });
      });

      if (!projectContext) {
        throw new Error(`Project context not found for ${projectId}`);
      }

      // Step 2: Execute Documentation Agent
      const result = await step.run("generate-documentation", async () => {
        return await documentationAgent.execute({
          taskId: taskId || `docs-${projectId}-${Date.now()}`,
          projectId,
          userId,
          conversationId,
          taskDetails: {
            title: "Documentation Generation",
            description: "Generate comprehensive project documentation",
            complexity: "simple",
            estimatedLines: 0,
            includeUserGuide: taskInput?.includeUserGuide ?? false,
            includeAPIDocs: taskInput?.includeAPIDocs ?? true,
            customSections: taskInput?.customSections || {},
          },
          context: {
            techStack: projectContext.techStack,
            architecture: projectContext.architecture,
            codebase: projectContext.codebase,
          },
        });
      });

      // Step 3: Handle result
      if (!result.success) {
        logger.error(`[Inngest] Documentation generation failed`, {
          projectId,
          error: result.error,
        });

        throw new Error(result.error || "Documentation generation failed");
      }

      const filesCreated = result.data?.filesCreated || [];
      const apiEndpoints = result.data?.apiEndpoints || [];
      const components = result.data?.components || [];

      logger.info(`[Inngest] Documentation generation complete`, {
        projectId,
        filesCreated: filesCreated.length,
        apiEndpoints: apiEndpoints.length,
        components: components.length,
      });

      // Step 4: Commit documentation files to Git
      if (taskInput?.commitToGit !== false && filesCreated.length > 0) {
        await step.run("commit-documentation", async () => {
          try {
            const gitTool = await import("@/lib/agents/tools/git-tool");

            // Stage documentation files
            await gitTool.GitTool.prototype.execute.call(
              { logExecution: () => {}, logError: () => {} },
              { operation: "add" },
              { projectId, userId }
            );

            // Commit
            const commitMessage = `docs: Generate comprehensive project documentation

Generated by Documentation Agent:
- ${filesCreated.join("\n- ")}

API Endpoints: ${apiEndpoints.length}
Components: ${components.length}
`;

            await gitTool.GitTool.prototype.execute.call(
              { logExecution: () => {}, logError: () => {} },
              { operation: "commit", message: commitMessage },
              { projectId, userId }
            );

            logger.info(`[Inngest] Documentation committed to git`, {
              projectId,
              filesCreated,
            });
          } catch (error) {
            logger.warn(`[Inngest] Failed to commit documentation`, {
              projectId,
              error,
            });
            // Don't fail the task if git commit fails
          }
        });
      }

      // Step 5: Send completion event
      await step.run("send-completion-event", async () => {
        await inngest.send({
          name: "agent/documentation.generate.complete",
          data: {
            taskId: taskId || `docs-${projectId}`,
            projectId,
            success: true,
            filesCreated,
            apiEndpoints: apiEndpoints.length,
            components: components.length,
            readmeCreated: filesCreated.includes("README.md"),
            apiDocsCreated: filesCreated.includes("docs/API.md"),
          },
        });
      });

      return {
        success: true,
        message: `Generated ${filesCreated.length} documentation files`,
        filesCreated,
        apiEndpoints: apiEndpoints.length,
        components: components.length,
      };
    } catch (error) {
      const errorMessage =
        error instanceof Error ? error.message : "Unknown error";

      logger.error(`[Inngest] Documentation Agent failed`, {
        projectId,
        error: errorMessage,
      });

      // Send failure event
      await step.run("send-failure-event", async () => {
        await inngest.send({
          name: "agent/documentation.generate.complete",
          data: {
            taskId: taskId || `docs-${projectId}`,
            projectId,
            success: false,
            error: errorMessage,
          },
        });
      });

      throw error;
    }
  }
);
