/**
 * Table-of-contents extractor.
 *
 * Parses the markdown source for H2 headings (and optionally H3
 * subsections) and returns a structured list the UI can render
 * as a sticky navigation rail. The same slugs are generated by
 * rehype-slug at render time, so the anchor hrefs match.
 */

export interface TocEntry {
  id:    string;
  title: string;
  level: 2 | 3;
}

/**
 * Convert a heading text into the GitHub-style slug rehype-slug
 * produces. Lowercases, replaces non-alphanumeric characters
 * with hyphens, collapses consecutive hyphens, trims leading
 * and trailing hyphens. Matches the default rehype-slug +
 * github-slugger algorithm closely enough for our TOC anchors.
 */
function slugify(text: string): string {
  return text
    .toLowerCase()
    // Remove emoji and other non-basic characters
    .replace(/[^\w\s-]/g, '')
    .replace(/\s+/g, '-')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '');
}

/**
 * Extract an ordered list of H2 headings from the markdown.
 * Only the top-level section headers are used — H3 subsection
 * headers are left out of the TOC to keep the rail clean on
 * long documents.
 */
export function extractToc(markdown: string): TocEntry[] {
  const lines = markdown.split('\n');
  const entries: TocEntry[] = [];
  // Track whether we're inside a fenced code block so we don't
  // pick up text that coincidentally starts with ##.
  let inFence = false;

  for (const line of lines) {
    if (line.startsWith('```')) {
      inFence = !inFence;
      continue;
    }
    if (inFence) continue;

    const match = line.match(/^(#{2,3})\s+(.+?)\s*$/);
    if (!match) continue;
    const level = match[1].length as 2 | 3;
    if (level !== 2) continue; // H3s excluded from TOC
    const title = match[2].trim();
    entries.push({ id: slugify(title), title, level });
  }

  return entries;
}
