// src/app/(app)/projects/[id]/documentation/page.tsx
"use client";

import { use, useState } from "react";
import useSWR from "swr";
import { motion, AnimatePresence } from "framer-motion";
import {
  ArrowLeft,
  BookOpen,
  FileText,
  Code,
  Layers,
  Download,
  Search,
  Loader2,
  AlertCircle,
  ChevronRight,
  Home,
} from "lucide-react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";

interface DocumentationPageProps {
  params: Promise<{
    id: string;
  }>;
}

interface DocSection {
  id: string;
  title: string;
  icon?: any;
  content: string;
}

// Icon mapping for documentation sections
const iconMap: Record<string, any> = {
  readme: BookOpen,
  api: Code,
  architecture: Layers,
  deployment: FileText,
};

const fetcher = async (url: string) => {
  const res = await fetch(url);
  if (!res.ok) {
    const contentType = res.headers.get("content-type");
    if (contentType && contentType.includes("application/json")) {
      const errorData = await res.json();
      throw new Error(errorData.error || `HTTP ${res.status}`);
    }
    throw new Error(`HTTP ${res.status}: ${res.statusText}`);
  }
  return res.json();
};

export default function DocumentationPage({ params }: DocumentationPageProps) {
  const { id: projectId } = use(params);
  const router = useRouter();
  const [activeSection, setActiveSection] = useState("readme");
  const [searchQuery, setSearchQuery] = useState("");

  // Fetch project data
  const { data: project, error: projectError } = useSWR(
    `/api/projects/${projectId}`,
    fetcher
  );

  // Fetch documentation from API
  const { data: documentationData, error: docError } = useSWR(
    `/api/projects/${projectId}/documentation`,
    fetcher
  );

  // Map documentation sections with icons
  const documentation: DocSection[] = (documentationData?.documentation || [
    {
      id: "readme",
      title: "README",
      icon: BookOpen,
      content: `# ${project?.name || "Project"} Documentation

## Overview

This project was built using NeuraLaunch's AI agent system, featuring automated code generation, testing, and deployment.

## Features

- **Full-Stack Application**: Complete frontend and backend implementation
- **Automated Testing**: Comprehensive test coverage with unit and integration tests
- **CI/CD Pipeline**: Automated deployment to preview and production environments
- **Quality Assurance**: Code review and security scanning included

## Tech Stack

- Frontend: React with Next.js
- Backend: Next.js API Routes
- Database: PostgreSQL with Prisma ORM
- Deployment: Vercel

## Getting Started

### Prerequisites

- Node.js 18+ installed
- npm or yarn package manager
- PostgreSQL database (local or remote)

### Installation

\`\`\`bash
# Clone the repository
git clone <repository-url>

# Install dependencies
npm install

# Set up environment variables
cp .env.example .env.local

# Run database migrations
npx prisma migrate dev

# Start development server
npm run dev
\`\`\`

Visit \`http://localhost:3000\` to view the application.

## Project Structure

\`\`\`
/src
  /app          # Next.js app router pages
  /components   # React components
  /lib          # Utility functions
  /types        # TypeScript types
/prisma         # Database schema and migrations
/public         # Static assets
\`\`\`

## Available Scripts

- \`npm run dev\` - Start development server
- \`npm run build\` - Build for production
- \`npm run start\` - Start production server
- \`npm run lint\` - Run ESLint
- \`npm test\` - Run tests

## Environment Variables

Create a \`.env.local\` file with the following variables:

\`\`\`
DATABASE_URL="postgresql://..."
NEXTAUTH_SECRET="your-secret"
NEXTAUTH_URL="http://localhost:3000"
\`\`\`

## Contributing

This project was generated by AI agents. For modifications, please review the code carefully and maintain the existing patterns.

## License

MIT License - See LICENSE file for details
`,
    },
    {
      id: "api",
      title: "API Documentation",
      icon: Code,
      content: `# API Documentation

## Base URL

\`\`\`
${typeof window !== "undefined" ? window.location.origin : "http://localhost:3000"}/api
\`\`\`

## Authentication

All API endpoints require authentication via NextAuth.js session cookies.

## Endpoints

### Projects

#### GET /api/projects

Get all projects for the authenticated user.

**Response:**
\`\`\`json
{
  "projects": [
    {
      "id": "string",
      "name": "string",
      "status": "active | completed | failed",
      "createdAt": "ISO8601",
      "updatedAt": "ISO8601"
    }
  ]
}
\`\`\`

#### GET /api/projects/[projectId]

Get a specific project by ID.

**Response:**
\`\`\`json
{
  "id": "string",
  "name": "string",
  "description": "string",
  "status": "string",
  "progress": 100,
  "createdAt": "ISO8601",
  "updatedAt": "ISO8601"
}
\`\`\`

#### DELETE /api/projects/[projectId]

Delete a project.

**Response:**
\`\`\`json
{
  "success": true,
  "message": "Project deleted successfully"
}
\`\`\`

### Tasks

#### GET /api/projects/[projectId]/tasks

Get all tasks for a project.

**Response:**
\`\`\`json
{
  "tasks": [
    {
      "id": "string",
      "agentName": "string",
      "status": "PENDING | RUNNING | COMPLETE | FAILED",
      "createdAt": "ISO8601"
    }
  ],
  "waves": []
}
\`\`\`

### Orchestrator

#### GET /api/orchestrator/status/[projectId]

Get orchestrator status for a project.

**Response:**
\`\`\`json
{
  "status": "running | completed | failed",
  "currentPhase": "string",
  "progress": 75,
  "activeAgents": ["BackendAgent", "FrontendAgent"],
  "currentWave": 2
}
\`\`\`

## Error Handling

All endpoints return standard HTTP status codes:

- \`200\` - Success
- \`401\` - Unauthorized
- \`404\` - Not Found
- \`500\` - Internal Server Error

Error response format:
\`\`\`json
{
  "error": "Error message"
}
\`\`\`

## Rate Limiting

API endpoints are rate-limited to prevent abuse:
- 100 requests per minute per user
- 1000 requests per hour per user
`,
    },
    {
      id: "architecture",
      title: "Architecture",
      icon: Layers,
      content: `# Architecture Overview (Fallback)

## System Architecture

This application follows a modern full-stack architecture built with Next.js 15 and the App Router.

## High-Level Components

\`\`\`
┌─────────────────────────────────────────┐
│         Client (Browser)                │
│  ┌────────────────────────────────────┐ │
│  │     Next.js App (React)            │ │
│  │  - Components                      │ │
│  │  - State Management (Zustand)      │ │
│  │  - Data Fetching (SWR)             │ │
│  └────────────────────────────────────┘ │
└─────────────────┬───────────────────────┘
                  │ HTTP/WebSocket
┌─────────────────▼───────────────────────┐
│         Next.js Server                  │
│  ┌────────────────────────────────────┐ │
│  │     API Routes                     │ │
│  │  - RESTful endpoints               │ │
│  │  - Authentication (NextAuth)       │ │
│  │  - Business logic                  │ │
│  └────────────────────────────────────┘ │
│  ┌────────────────────────────────────┐ │
│  │     AI Agent System                │ │
│  │  - Orchestrator                    │ │
│  │  - 13+ Specialized Agents          │ │
│  │  - Event-driven (Inngest)          │ │
│  └────────────────────────────────────┘ │
└─────────────────┬───────────────────────┘
                  │
┌─────────────────▼───────────────────────┐
│         Database Layer                  │
│  ┌────────────────────────────────────┐ │
│  │     PostgreSQL + Prisma ORM        │ │
│  │  - Project data                    │ │
│  │  - User sessions                   │ │
│  │  - Task tracking                   │ │
│  └────────────────────────────────────┘ │
└─────────────────────────────────────────┘
\`\`\`

## Frontend Architecture

### Component Structure

- **Pages**: Next.js App Router pages in \`src/app\`
- **Components**: Reusable React components in \`src/components\`
- **Hooks**: Custom React hooks in \`src/hooks\`
- **Stores**: Zustand state management in \`src/stores\`

### Data Flow

1. Components use SWR hooks to fetch data from API routes
2. SWR provides caching, revalidation, and optimistic updates
3. Zustand stores manage global application state
4. Real-time updates via polling (3-5 second intervals)

### UI Framework

- **shadcn/ui**: Pre-built accessible components
- **Tailwind CSS**: Utility-first CSS framework
- **Framer Motion**: Animation library

## Backend Architecture

### API Layer

- RESTful API routes in \`src/app/api\`
- NextAuth.js for authentication
- Session-based authorization
- Input validation with Zod

### AI Agent System

#### Orchestrator Pattern

The orchestrator coordinates multiple specialized AI agents:

1. **Planning Phase**
   - Analyzer Agent: Extracts requirements
   - Research Agent: Finds best practices
   - Validation Agent: Checks feasibility
   - Planning Agent: Creates execution plan

2. **Execution Phase**
   - Backend Agent: Builds API and database
   - Frontend Agent: Creates UI components
   - Infrastructure Agent: Sets up DevOps

3. **Quality Phase**
   - Testing Agent: Writes and runs tests
   - Critic Agent: Reviews code quality
   - Integration Agent: Verifies integration

4. **Deployment Phase**
   - Deployment Agent: Deploys to platforms
   - Documentation Agent: Generates docs
   - Monitoring Agent: Sets up monitoring

#### Wave-Based Execution

Tasks are organized into waves for parallel execution:
- Max 3 tasks per agent per wave
- Waves execute sequentially
- Quality gates between waves
- Automatic retry on failure

### Database Schema

Key models:
- \`User\`: User accounts and profiles
- \`Conversation\`: Projects and their metadata
- \`Message\`: Chat messages and interactions
- \`Task\`: Agent tasks and execution status
- \`LandingPage\`: Generated landing pages

## Security

- HTTPS-only in production
- CSRF protection via NextAuth
- SQL injection prevention via Prisma
- XSS protection via React
- Rate limiting on API endpoints
- Input validation and sanitization

## Scalability

- Stateless API design
- Database connection pooling
- Edge caching with Vercel
- Async job processing with Inngest
- Horizontal scaling ready

## Monitoring

- Error tracking and logging
- Performance monitoring
- Database query optimization
- API response time tracking
- User analytics

## Deployment

- Vercel for hosting
- PostgreSQL database
- GitHub for version control
- Automated CI/CD pipeline
- Preview deployments for PRs
`,
    },
  ]).map((doc: DocSection) => ({
    ...doc,
    icon: iconMap[doc.id] || BookOpen, // Add icon based on section ID
  }));

  if (projectError || docError) {
    return (
      <div className="min-h-screen bg-background flex items-center justify-center p-4">
        <Card className="max-w-md w-full">
          <CardHeader>
            <CardTitle className="flex items-center gap-2 text-destructive">
              <AlertCircle className="w-5 h-5" />
              Error Loading Documentation
            </CardTitle>
          </CardHeader>
          <CardContent>
            <p className="text-muted-foreground mb-4">
              {projectError?.message || docError?.message || "Failed to load project documentation"}
            </p>
            <Button onClick={() => router.push("/projects")}>
              <ArrowLeft className="w-4 h-4 mr-2" />
              Back to Projects
            </Button>
          </CardContent>
        </Card>
      </div>
    );
  }

  if (!project || !documentationData) {
    return (
      <div className="min-h-screen bg-background flex items-center justify-center">
        <div className="text-center">
          <Loader2 className="w-12 h-12 animate-spin text-primary mx-auto mb-4" />
          <p className="text-muted-foreground">Loading documentation...</p>
        </div>
      </div>
    );
  }

  const filteredDocs = documentation.filter(
    (doc) =>
      searchQuery === "" ||
      doc.title.toLowerCase().includes(searchQuery.toLowerCase()) ||
      doc.content.toLowerCase().includes(searchQuery.toLowerCase())
  );

  const activeDoc = documentation.find((doc) => doc.id === activeSection) || documentation[0];

  return (
    <div className="min-h-screen bg-background">
      {/* Header */}
      <div className="border-b bg-card/50 backdrop-blur supports-[backdrop-filter]:bg-card/50 sticky top-0 z-10">
        <div className="container mx-auto px-4 py-4">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-4">
              <Link href={`/projects/${projectId}`}>
                <Button variant="ghost" size="sm">
                  <ArrowLeft className="w-4 h-4 mr-2" />
                  Back to Project
                </Button>
              </Link>
              <div className="flex items-center gap-2">
                <BookOpen className="w-6 h-6 text-primary" />
                <div>
                  <h1 className="text-2xl font-bold text-foreground">Documentation</h1>
                  <p className="text-sm text-muted-foreground">{project.name}</p>
                </div>
              </div>
            </div>

            {/* Breadcrumb */}
            <div className="hidden md:flex items-center gap-2 text-sm text-muted-foreground">
              <Link href="/projects" className="hover:text-foreground">
                <Home className="w-4 h-4" />
              </Link>
              <ChevronRight className="w-4 h-4" />
              <Link href={`/projects/${projectId}`} className="hover:text-foreground">
                {project.name}
              </Link>
              <ChevronRight className="w-4 h-4" />
              <span className="text-foreground">Documentation</span>
            </div>
          </div>
        </div>
      </div>

      <div className="container mx-auto px-4 py-8">
        <div className="grid lg:grid-cols-[280px_1fr] gap-8">
          {/* Sidebar */}
          <div className="space-y-4">
            {/* Search */}
            <div className="relative">
              <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-muted-foreground" />
              <Input
                placeholder="Search documentation..."
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                className="pl-9"
              />
            </div>

            {/* Navigation */}
            <Card>
              <CardHeader>
                <CardTitle className="text-sm font-medium">Contents</CardTitle>
              </CardHeader>
              <CardContent className="space-y-1 p-3">
                {filteredDocs.map((doc) => (
                  <motion.button
                    key={doc.id}
                    onClick={() => setActiveSection(doc.id)}
                    whileHover={{ x: 4 }}
                    className={`w-full flex items-center gap-3 px-3 py-2 rounded-lg text-sm transition-colors ${
                      activeSection === doc.id
                        ? "bg-primary text-primary-foreground"
                        : "text-muted-foreground hover:bg-muted hover:text-foreground"
                    }`}
                  >
                    <doc.icon className="w-4 h-4" />
                    {doc.title}
                  </motion.button>
                ))}
              </CardContent>
            </Card>

            {/* Actions */}
            <Card>
              <CardContent className="p-3 space-y-2">
                <Button variant="outline" size="sm" className="w-full justify-start">
                  <Download className="w-4 h-4 mr-2" />
                  Export as PDF
                </Button>
                <Button variant="outline" size="sm" className="w-full justify-start">
                  <FileText className="w-4 h-4 mr-2" />
                  Download Markdown
                </Button>
              </CardContent>
            </Card>
          </div>

          {/* Main Content */}
          <AnimatePresence mode="wait">
            <motion.div
              key={activeSection}
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -20 }}
              transition={{ duration: 0.2 }}
            >
              <Card>
                <CardHeader>
                  <div className="flex items-center gap-3">
                    <div className="p-2 rounded-lg bg-primary/10 text-primary">
                      <activeDoc.icon className="w-5 h-5" />
                    </div>
                    <CardTitle className="text-2xl">{activeDoc.title}</CardTitle>
                  </div>
                </CardHeader>
                <CardContent>
                  <div className="prose prose-sm dark:prose-invert max-w-none">
                    <ReactMarkdown remarkPlugins={[remarkGfm]}>
                      {activeDoc.content}
                    </ReactMarkdown>
                  </div>
                </CardContent>
              </Card>
            </motion.div>
          </AnimatePresence>
        </div>
      </div>
    </div>
  );
}
