// src/lib/validation/schemas.ts
import { z } from 'zod';

// ---------------------------------------------------------------------------
// Length caps — bound every wire-protocol string (analytics events) to
// prevent DoS via multi-MB JSON. LLM-output schemas DELIBERATELY do NOT
// reuse these aliases — Anthropic structured-output rejects strict
// length constraints (see ValidationPageContentSchema below). LLM
// fields use bare z.string() and are clamped post-parse via the
// clampString helper.
// ---------------------------------------------------------------------------

const SHORT_TEXT   = z.string().min(1).max(200);
const ANSWER_TEXT  = z.string().min(1).max(500);

// Post-parse clamp helper. Anthropic structured-output does not enforce
// string-length limits during generation (see comment block on
// ValidationPageContentSchema below), so every LLM-output schema in
// this file uses bare z.string() and clamps server-side via this
// helper. The trailing ellipsis signals to the renderer that the model
// went over its soft target — useful when triaging which prompts need
// length retuning.
const clampString = (max: number) => (s: string) =>
  s.length > max
    ? `${s.slice(0, Math.max(0, max - 1))}…`
    : s;

// ---------------------------------------------------------------------------
// Page content — generated by Claude from recommendationId
// ---------------------------------------------------------------------------
//
// IMPORTANT: every text field below is bare `z.string()` with NO .max()
// (and NO .min()). Anthropic's structured-output endpoint does NOT
// consistently enforce string-length limits during generation — the
// model produces a longer string, the response is structurally valid
// JSON, and the AI SDK's post-hoc Zod parse rejects the whole thing as
// AI_NoObjectGeneratedError. The page generator inherits the same
// fragility documented in the ValidationInterpretationSchema block
// further down (production hit on 2026-04-08); the fix shape is
// identical: keep the length intent in the `.describe()` copy + the
// synthesis prompt, and post-clamp via the helpers below. The
// persisted JSONB column stays bounded; the model just isn't punished
// for going slightly over the soft target.
//
// Same array-cardinality story too: Anthropic structured-output rejects
// minItems > 1 and any maxItems, so the array length rules live in the
// .superRefine() block on ValidationPageContentSchema.

const clampPage = {
  headline:           clampString(400),
  subheadline:        clampString(1_000),
  problemStatement:   clampString(4_000),
  solutionStatement:  clampString(4_000),
  ctaHeadline:        clampString(400),
  ctaButtonLabel:     clampString(80),
  ctaPlaceholder:     clampString(160),
  entrySurveyQuestion: clampString(400),
  exitSurveyQuestion:  clampString(400),
  metaTitle:          clampString(120),
  metaDescription:    clampString(320),
  taskId:             clampString(200),
  featureTitle:       clampString(400),
  featureDescription: clampString(1_000),
  featureBenefit:     clampString(1_000),
  surveyOptionId:     clampString(200),
  surveyOptionLabel:  clampString(400),
};

export const FeatureCardSchema = z.object({
  taskId:      z.string().describe('The roadmap task ID this feature maps to. Aim for under 100 chars; server hard-truncates at 200.'),
  title:       z.string().describe('Feature name — short, specific, verb-free (e.g. "Automated invoicing"). Aim for under 200 chars; server hard-truncates at 400.'),
  description: z.string().describe('One sentence: what this feature does for the user, in plain language. Aim for under 500 chars; server hard-truncates at 1000.'),
  benefit:     z.string().describe('One sentence: the concrete outcome the user gets from this feature. Aim for under 500 chars; server hard-truncates at 1000.'),
});

export const SurveyOptionSchema = z.object({
  id:    z.string().describe('Stable id slug. Aim for under 100 chars; server hard-truncates at 200.'),
  label: z.string().describe('Short option label shown to the user. Aim for under 200 chars; server hard-truncates at 400.'),
});

export const ValidationPageContentSchema = z.object({
  headline:            z.string().describe('Main headline — one punchy sentence, problem-first, no jargon. Aim for under 200 chars; server hard-truncates at 400.'),
  subheadline:         z.string().describe('Supporting sentence expanding the headline — specific to their market. Aim for under 500 chars; server hard-truncates at 1000.'),
  problemStatement:    z.string().describe('2–3 sentences: the exact pain this solves, in the target user\'s own language. Aim for under 2000 chars; server hard-truncates at 4000.'),
  solutionStatement:   z.string().describe('2–3 sentences: how this product solves it — specific, not generic. Aim for under 2000 chars; server hard-truncates at 4000.'),
  features:            z.array(FeatureCardSchema).describe('Between 2 and 6 feature cards. Never fewer than 2, never more than 6.'),
  ctaHeadline:         z.string().describe('Call-to-action headline above the signup form. Aim for under 200 chars; server hard-truncates at 400.'),
  ctaButtonLabel:      z.string().describe('Button label — 2–4 words, action-oriented. Aim for under 40 chars; server hard-truncates at 80.'),
  ctaPlaceholder:      z.string().describe('Email input placeholder text. Aim for under 80 chars; server hard-truncates at 160.'),
  entrySurveyQuestion: z.string().describe('Entry survey question. Aim for under 200 chars; server hard-truncates at 400.'),
  entrySurveyOptions:  z.array(SurveyOptionSchema).describe('Between 2 and 4 entry survey options'),
  exitSurveyQuestion:  z.string().describe('Exit survey question. Aim for under 200 chars; server hard-truncates at 400.'),
  exitSurveyOptions:   z.array(SurveyOptionSchema).describe('Between 2 and 4 exit survey options'),
  metaTitle:           z.string().describe('Page title for SEO/sharing. Aim for under 60 chars; server hard-truncates at 120.'),
  metaDescription:     z.string().describe('Page description for sharing cards. Aim for under 160 chars; server hard-truncates at 320.'),
}).superRefine((data, ctx) => {
  if (data.features.length < 2 || data.features.length > 6) {
    ctx.addIssue({ code: 'custom', path: ['features'], message: 'features must have between 2 and 6 entries' });
  }
  if (data.entrySurveyOptions.length < 2 || data.entrySurveyOptions.length > 4) {
    ctx.addIssue({ code: 'custom', path: ['entrySurveyOptions'], message: 'entrySurveyOptions must have between 2 and 4 entries' });
  }
  if (data.exitSurveyOptions.length < 2 || data.exitSurveyOptions.length > 4) {
    ctx.addIssue({ code: 'custom', path: ['exitSurveyOptions'], message: 'exitSurveyOptions must have between 2 and 4 entries' });
  }
}).transform(data => ({
  ...data,
  headline:            clampPage.headline(data.headline),
  subheadline:         clampPage.subheadline(data.subheadline),
  problemStatement:    clampPage.problemStatement(data.problemStatement),
  solutionStatement:   clampPage.solutionStatement(data.solutionStatement),
  ctaHeadline:         clampPage.ctaHeadline(data.ctaHeadline),
  ctaButtonLabel:      clampPage.ctaButtonLabel(data.ctaButtonLabel),
  ctaPlaceholder:      clampPage.ctaPlaceholder(data.ctaPlaceholder),
  entrySurveyQuestion: clampPage.entrySurveyQuestion(data.entrySurveyQuestion),
  exitSurveyQuestion:  clampPage.exitSurveyQuestion(data.exitSurveyQuestion),
  metaTitle:           clampPage.metaTitle(data.metaTitle),
  metaDescription:     clampPage.metaDescription(data.metaDescription),
  features: data.features.map(f => ({
    ...f,
    taskId:      clampPage.taskId(f.taskId),
    title:       clampPage.featureTitle(f.title),
    description: clampPage.featureDescription(f.description),
    benefit:     clampPage.featureBenefit(f.benefit),
  })),
  entrySurveyOptions: data.entrySurveyOptions.map(o => ({
    ...o,
    id:    clampPage.surveyOptionId(o.id),
    label: clampPage.surveyOptionLabel(o.label),
  })),
  exitSurveyOptions: data.exitSurveyOptions.map(o => ({
    ...o,
    id:    clampPage.surveyOptionId(o.id),
    label: clampPage.surveyOptionLabel(o.label),
  })),
}));

export type FeatureCard           = z.infer<typeof FeatureCardSchema>;
export type ValidationPageContent = z.infer<typeof ValidationPageContentSchema>;

// ---------------------------------------------------------------------------
// Distribution brief — generated at publish time (LLM output)
// ---------------------------------------------------------------------------
//
// Same no-.max() / no-.min() rule as the page-content schema above.
// The synthesis prompt carries the soft length targets; the post-clamp
// .transform() at the array level enforces hard ceilings on receipt.

const clampDist = {
  channel:        clampString(400),
  message:        clampString(4_000),
  expectedYield:  clampString(1_000),
  audienceReason: clampString(1_000),
};

export const DistributionChannelSchema = z.object({
  channel:        z.string().describe('Specific channel name — never a category. Aim for under 200 chars; server hard-truncates at 400.'),
  message:        z.string().describe('The exact message to send — written in the founder\'s voice. Aim for under 2000 chars; server hard-truncates at 4000.'),
  expectedYield:  z.string().describe('Honest, realistic yield estimate. Aim for under 500 chars; server hard-truncates at 1000.'),
  audienceReason: z.string().describe('One sentence: why this channel for this specific person and market. Aim for under 500 chars; server hard-truncates at 1000.'),
});

/**
 * Distribution brief: exactly three channels, channel names must be unique
 * so per-channel completion toggling is unambiguous in the UI.
 *
 * Anthropic's structured output rejects both array minItems and maxItems
 * constraints, so the schema is unconstrained at the type level. The
 * cardinality and uniqueness rules are enforced via .superRefine() and
 * the synthesis prompt instructs the model to produce exactly three.
 * Per-field length clamping happens in the .transform() below.
 */
export const DistributionBriefSchema = z.array(DistributionChannelSchema)
  .superRefine((channels, ctx) => {
    if (channels.length !== 3) {
      ctx.addIssue({ code: 'custom', message: 'Distribution brief must contain exactly 3 channels' });
    }
    if (new Set(channels.map(c => c.channel.trim().toLowerCase())).size !== channels.length) {
      ctx.addIssue({ code: 'custom', message: 'Channel names must be unique' });
    }
  })
  .transform(channels => channels.map(c => ({
    channel:        clampDist.channel(c.channel),
    message:        clampDist.message(c.message),
    expectedYield:  clampDist.expectedYield(c.expectedYield),
    audienceReason: clampDist.audienceReason(c.audienceReason),
  })));

export type DistributionChannel = z.infer<typeof DistributionChannelSchema>;
export type DistributionBrief   = z.infer<typeof DistributionBriefSchema>;

// ---------------------------------------------------------------------------
// Analytics event properties — bound all strings and keep the shape tight
// ---------------------------------------------------------------------------

export const AnalyticsEventSchema = z.discriminatedUnion('event', [
  z.object({
    slug:  z.string().min(1).max(120),
    event: z.literal('page_view'),
  }),
  z.object({
    slug:  z.string().min(1).max(120),
    event: z.literal('scroll_depth'),
    depth: z.number().int().min(0).max(100),
  }),
  z.object({
    slug:  z.string().min(1).max(120),
    event: z.literal('exit_intent'),
  }),
  z.object({
    slug:   z.string().min(1).max(120),
    event:  z.literal('feature_click'),
    taskId: z.string().min(1).max(100),
    title:  z.string().min(1).max(200),
  }),
  z.object({
    slug:  z.string().min(1).max(120),
    event: z.literal('cta_signup'),
    email: z.string().email().max(254),
  }),
  z.object({
    slug:      z.string().min(1).max(120),
    event:     z.literal('survey_response'),
    surveyKey: z.enum(['entry', 'exit']),
    answerId:  z.string().min(1).max(100),
    answer:    ANSWER_TEXT,
    question:  SHORT_TEXT,
  }),
]);

export type AnalyticsEvent = z.infer<typeof AnalyticsEventSchema>;

// ---------------------------------------------------------------------------
// Snapshot analytics — aggregated per reporting cycle
// ---------------------------------------------------------------------------

export const FeatureClickDataSchema = z.object({
  taskId: z.string(),
  title:  z.string(),
  clicks: z.number().int().min(0),
});

export const SurveyResponseSchema = z.object({
  question: z.string(),
  answer:   z.string(),
  takenAt:  z.string(),
});

export const TrafficSourceSchema = z.object({
  source: z.string(),
  count:  z.number().int().min(0),
});

export const ScrollDepthSchema = z.object({
  depth:             z.number(),
  reachedPercentage: z.number(),
});

export type FeatureClickData = z.infer<typeof FeatureClickDataSchema>;
export type SurveyResponse   = z.infer<typeof SurveyResponseSchema>;

// ---------------------------------------------------------------------------
// Interpretation — Step 1 Sonnet output
// ---------------------------------------------------------------------------

// IMPORTANT: every text field on this schema is bare `z.string()`
// with NO .max() constraint. Anthropic's structured-output endpoint
// does NOT consistently enforce string-length limits during
// generation — the model produces a longer string than the cap, the
// response is structurally valid JSON, and then the AI SDK's post-hoc
// Zod parse rejects the whole thing as AI_NoObjectGeneratedError.
//
// Production hit this on 2026-04-08 18:01 UTC: the Gap 1
// low-traffic-pivot interpreter prompt asks for a multi-sentence
// operational nextAction (typically 400-700 characters) but the
// schema capped MEDIUM_TEXT at 500. The interpreter just bypassed
// the cap and the entire validation reporting Inngest function
// 500'd at the parse step, leaving the founder with no report.
//
// Same fix shape we used on the pushback schema yesterday: drop the
// schema-level .max(), keep length intent in the prompt + describe()
// copy, enforce bounds via the .transform() post-clamp helpers
// below. The persisted JSONB column is still bounded; the model is
// just not punished for going slightly over the soft target.
// (clampString helper is hoisted to the top of this file so the
//  page-content schema above can reuse it.)
const clampInterpretation = {
  signalReason:         clampString(400),  // soft "one sentence" — 400 char cap
  conversionAssessment: clampString(400),
  trafficAssessment:    clampString(400),
  nextAction:           clampString(2_000), // multi-sentence operational guidance
  surveyTheme:          clampString(400),
};

export const ValidationInterpretationSchema = z.object({
  signalStrength:       z.enum(['strong', 'moderate', 'weak', 'negative', 'insufficient']),
  signalReason:         z.string().describe('One sentence explaining the signal strength score with the number behind it. Aim for under 200 characters; the server hard-truncates at 400.'),
  featureRanking:       z.array(z.object({
    taskId:     z.string(),
    title:      z.string(),
    clicks:     z.number(),
    percentage: z.number(),
    assessment: z.string(),
  })),
  conversionAssessment: z.string().describe('One sentence on conversion. Aim for under 200 characters; the server hard-truncates at 400.'),
  // No .max() — Anthropic structured output rejects array maxItems.
  // The prompt instructs the model to return at most 8 themes; we
  // post-clamp the array on receipt to enforce that ceiling.
  surveyThemes:         z.array(z.string()).describe('Up to 8 themes — never more. Aim for under 200 characters per theme; server hard-truncates at 400.'),
  trafficAssessment:    z.string().describe('One sentence on traffic. Aim for under 200 characters; the server hard-truncates at 400.'),
  nextAction:           z.string().describe('Operational instruction. For low-traffic and distribution-stalled cases this is multi-sentence guidance. Aim for under 1000 characters; the server hard-truncates at 2000.'),
}).transform(data => ({
  ...data,
  signalReason:         clampInterpretation.signalReason(data.signalReason),
  conversionAssessment: clampInterpretation.conversionAssessment(data.conversionAssessment),
  trafficAssessment:    clampInterpretation.trafficAssessment(data.trafficAssessment),
  nextAction:           clampInterpretation.nextAction(data.nextAction),
  surveyThemes:         data.surveyThemes
    .slice(0, 8)
    .map(clampInterpretation.surveyTheme),
}));

export type ValidationInterpretation = z.infer<typeof ValidationInterpretationSchema>;

// ---------------------------------------------------------------------------
// Report — Step 2 Opus output (gated behind thresholds)
// ---------------------------------------------------------------------------

// Bare z.string() for the same reason as the interpretation schema
// above — Anthropic does not enforce string length during structured
// output generation. The .transform() on ValidationReportSchema below
// post-clamps every text field on these subschemas.
export const ConfirmedFeatureSchema = z.object({
  taskId:     z.string(),
  title:      z.string(),
  clicks:     z.number(),
  percentage: z.number(),
  evidence:   z.string(),
});

export const RejectedFeatureSchema = z.object({
  taskId: z.string(),
  title:  z.string(),
  clicks: z.number(),
  reason: z.string(),
});

/**
 * The committed build brief. `buildBrief` is always populated:
 *   - For 'strong' | 'moderate' | 'weak' → "Build X. Defer Y. Cut Z." style
 *   - For 'negative' → honest "do not build this because..." paragraph
 *
 * When signalStrength === 'negative', the following fields MUST also be
 * populated:
 *   - disconfirmedAssumptions: which specific assumptions from the original
 *     recommendation the market contradicted
 *   - pivotOptions: 2–3 adjacent paths the founder could try with the same
 *     belief state; empty array means "kill this direction, new discovery"
 *
 * For non-negative signals these fields are empty arrays.
 */
// No .max() on disconfirmedAssumptions or pivotOptions — Anthropic
// rejects array maxItems. The prompt instructs the model to return
// at most 5 / 3 entries; we post-clamp to enforce on receipt.
// .default([]) is also dropped because superRefine and transform run
// before defaults at parse time and the model is required to return
// the field anyway.
const clampReport = {
  evidence:        clampString(2_000),  // build brief evidence per feature
  reason:          clampString(2_000),  // build brief rejection reason per feature
  surveyInsights:  clampString(4_000),  // multi-paragraph qualitative summary
  buildBrief:      clampString(4_000),  // multi-paragraph "build X / cut Y" call
  nextAction:      clampString(2_000),  // operational prescription
  disconfirmedAssumption: clampString(1_000),
  pivotTitle:      clampString(400),
  pivotRationale:  clampString(2_000),
};

export const ValidationReportSchema = z.object({
  signalStrength:          z.enum(['strong', 'moderate', 'weak', 'negative']),
  confirmedFeatures:       z.array(ConfirmedFeatureSchema),
  rejectedFeatures:        z.array(RejectedFeatureSchema),
  surveyInsights:          z.string().describe('Multi-paragraph qualitative summary. Aim for under 2000 chars; server hard-truncates at 4000.'),
  buildBrief:              z.string().describe('Multi-paragraph build / cut / defer call. Aim for under 2000 chars; server hard-truncates at 4000.'),
  nextAction:              z.string().describe('Operational instruction. Aim for under 1000 chars; server hard-truncates at 2000.'),
  disconfirmedAssumptions: z.array(z.string()).describe('Up to 5 disconfirmed assumptions when signalStrength is negative; empty array otherwise. Aim for under 500 chars per item; server hard-truncates at 1000.'),
  pivotOptions:            z.array(z.object({
    title:    z.string(),
    rationale: z.string(),
  })).describe('Up to 3 pivot options when signalStrength is negative; empty array otherwise.'),
}).transform(data => ({
  ...data,
  surveyInsights:          clampReport.surveyInsights(data.surveyInsights),
  buildBrief:              clampReport.buildBrief(data.buildBrief),
  nextAction:              clampReport.nextAction(data.nextAction),
  confirmedFeatures:       data.confirmedFeatures.map(f => ({
    ...f,
    evidence: clampReport.evidence(f.evidence),
  })),
  rejectedFeatures:        data.rejectedFeatures.map(f => ({
    ...f,
    reason: clampReport.reason(f.reason),
  })),
  disconfirmedAssumptions: data.disconfirmedAssumptions
    .slice(0, 5)
    .map(clampReport.disconfirmedAssumption),
  pivotOptions:            data.pivotOptions.slice(0, 3).map(p => ({
    title:     clampReport.pivotTitle(p.title),
    rationale: clampReport.pivotRationale(p.rationale),
  })),
}));

export type ConfirmedFeature = z.infer<typeof ConfirmedFeatureSchema>;
export type RejectedFeature  = z.infer<typeof RejectedFeatureSchema>;
export type ValidationReport = z.infer<typeof ValidationReportSchema>;
