// src/lib/validation/schemas.ts
import { z } from 'zod';

// ---------------------------------------------------------------------------
// Length caps — bound every user-facing / LLM-facing string to prevent
// both DoS (multi-MB JSON) and prompt-injection amplification.
// ---------------------------------------------------------------------------

const SHORT_TEXT   = z.string().min(1).max(200);
const MEDIUM_TEXT  = z.string().min(1).max(500);
const LONG_TEXT    = z.string().min(1).max(2_000);
const ANSWER_TEXT  = z.string().min(1).max(500);

// ---------------------------------------------------------------------------
// Page content — generated by Claude from recommendationId
// ---------------------------------------------------------------------------

export const FeatureCardSchema = z.object({
  taskId:      z.string().min(1).max(100).describe('The roadmap task ID this feature maps to'),
  title:       SHORT_TEXT.describe('Feature name — short, specific, verb-free (e.g. "Automated invoicing")'),
  description: MEDIUM_TEXT.describe('One sentence: what this feature does for the user, in plain language'),
  benefit:     MEDIUM_TEXT.describe('One sentence: the concrete outcome the user gets from this feature'),
});

export const SurveyOptionSchema = z.object({
  id:    z.string().min(1).max(100),
  label: SHORT_TEXT.describe('Short option label shown to the user'),
});

// Anthropic structured-output JSON Schema only supports array minItems
// of 0 or 1 — it rejects any other lower bound at the API level. We
// therefore drop .min(>=2) and .length(N) constraints from the schemas
// the LLM sees and re-enforce them via .superRefine() at validation time.
// This means the model is told "an array of X" without a lower bound,
// and we reject the response after the call if it doesn't meet the real
// minimum. Upper bounds (.max) are supported and stay in place.
export const ValidationPageContentSchema = z.object({
  headline:         SHORT_TEXT.describe('Main headline — one punchy sentence, problem-first, no jargon'),
  subheadline:      MEDIUM_TEXT.describe('Supporting sentence expanding the headline — specific to their market'),
  problemStatement: LONG_TEXT.describe('2–3 sentences: the exact pain this solves, in the target user\'s own language'),
  solutionStatement: LONG_TEXT.describe('2–3 sentences: how this product solves it — specific, not generic'),
  features:         z.array(FeatureCardSchema).max(6).describe('Between 2 and 6 feature cards — fewer than 2 is an error'),
  ctaHeadline:      SHORT_TEXT.describe('Call-to-action headline above the signup form'),
  ctaButtonLabel:   z.string().min(1).max(40).describe('Button label — 2–4 words, action-oriented'),
  ctaPlaceholder:   z.string().min(1).max(80).describe('Email input placeholder text'),
  entrySurveyQuestion: SHORT_TEXT,
  entrySurveyOptions:  z.array(SurveyOptionSchema).max(4).describe('Between 2 and 4 entry survey options'),
  exitSurveyQuestion:  SHORT_TEXT,
  exitSurveyOptions:   z.array(SurveyOptionSchema).max(4).describe('Between 2 and 4 exit survey options'),
  metaTitle:        z.string().min(1).max(60).describe('Page title for SEO/sharing — under 60 characters'),
  metaDescription:  z.string().min(1).max(160).describe('Page description for sharing cards — under 160 characters'),
}).superRefine((data, ctx) => {
  if (data.features.length < 2) {
    ctx.addIssue({ code: 'custom', path: ['features'], message: 'features must have at least 2 entries' });
  }
  if (data.entrySurveyOptions.length < 2) {
    ctx.addIssue({ code: 'custom', path: ['entrySurveyOptions'], message: 'entrySurveyOptions must have at least 2 entries' });
  }
  if (data.exitSurveyOptions.length < 2) {
    ctx.addIssue({ code: 'custom', path: ['exitSurveyOptions'], message: 'exitSurveyOptions must have at least 2 entries' });
  }
});

export type FeatureCard           = z.infer<typeof FeatureCardSchema>;
export type ValidationPageContent = z.infer<typeof ValidationPageContentSchema>;

// ---------------------------------------------------------------------------
// Distribution brief — generated at publish time
// ---------------------------------------------------------------------------

export const DistributionChannelSchema = z.object({
  channel:        SHORT_TEXT.describe('Specific channel name — never a category'),
  message:        LONG_TEXT.describe('The exact message to send — written in the founder\'s voice'),
  expectedYield:  MEDIUM_TEXT.describe('Honest, realistic yield estimate'),
  audienceReason: MEDIUM_TEXT.describe('One sentence: why this channel for this specific person and market'),
});

/**
 * Distribution brief: exactly three channels, channel names must be unique
 * so per-channel completion toggling is unambiguous in the UI.
 *
 * The exact-3 cardinality is enforced via .superRefine() rather than
 * .length(3) so the JSON Schema we hand to Anthropic does not include
 * an unsupported `minItems: 3`. The model is instructed to return three
 * via `max(3)` plus the prompt copy; we reject the response if it does
 * not.
 */
export const DistributionBriefSchema = z.array(DistributionChannelSchema)
  .max(3)
  .superRefine((channels, ctx) => {
    if (channels.length !== 3) {
      ctx.addIssue({ code: 'custom', message: 'Distribution brief must contain exactly 3 channels' });
    }
    if (new Set(channels.map(c => c.channel.trim().toLowerCase())).size !== channels.length) {
      ctx.addIssue({ code: 'custom', message: 'Channel names must be unique' });
    }
  });

export type DistributionChannel = z.infer<typeof DistributionChannelSchema>;
export type DistributionBrief   = z.infer<typeof DistributionBriefSchema>;

// ---------------------------------------------------------------------------
// Analytics event properties — bound all strings and keep the shape tight
// ---------------------------------------------------------------------------

export const AnalyticsEventSchema = z.discriminatedUnion('event', [
  z.object({
    slug:  z.string().min(1).max(120),
    event: z.literal('page_view'),
  }),
  z.object({
    slug:  z.string().min(1).max(120),
    event: z.literal('scroll_depth'),
    depth: z.number().int().min(0).max(100),
  }),
  z.object({
    slug:  z.string().min(1).max(120),
    event: z.literal('exit_intent'),
  }),
  z.object({
    slug:   z.string().min(1).max(120),
    event:  z.literal('feature_click'),
    taskId: z.string().min(1).max(100),
    title:  z.string().min(1).max(200),
  }),
  z.object({
    slug:  z.string().min(1).max(120),
    event: z.literal('cta_signup'),
    email: z.string().email().max(254),
  }),
  z.object({
    slug:      z.string().min(1).max(120),
    event:     z.literal('survey_response'),
    surveyKey: z.enum(['entry', 'exit']),
    answerId:  z.string().min(1).max(100),
    answer:    ANSWER_TEXT,
    question:  SHORT_TEXT,
  }),
]);

export type AnalyticsEvent = z.infer<typeof AnalyticsEventSchema>;

// ---------------------------------------------------------------------------
// Snapshot analytics — aggregated per reporting cycle
// ---------------------------------------------------------------------------

export const FeatureClickDataSchema = z.object({
  taskId: z.string(),
  title:  z.string(),
  clicks: z.number().int().min(0),
});

export const SurveyResponseSchema = z.object({
  question: z.string(),
  answer:   z.string(),
  takenAt:  z.string(),
});

export const TrafficSourceSchema = z.object({
  source: z.string(),
  count:  z.number().int().min(0),
});

export const ScrollDepthSchema = z.object({
  depth:             z.number(),
  reachedPercentage: z.number(),
});

export type FeatureClickData = z.infer<typeof FeatureClickDataSchema>;
export type SurveyResponse   = z.infer<typeof SurveyResponseSchema>;

// ---------------------------------------------------------------------------
// Interpretation — Step 1 Sonnet output
// ---------------------------------------------------------------------------

export const ValidationInterpretationSchema = z.object({
  signalStrength:       z.enum(['strong', 'moderate', 'weak', 'negative', 'insufficient']),
  signalReason:         SHORT_TEXT.describe('One sentence explaining the signal strength score with the number behind it'),
  featureRanking:       z.array(z.object({
    taskId:     z.string(),
    title:      z.string(),
    clicks:     z.number(),
    percentage: z.number(),
    assessment: z.string(),
  })),
  conversionAssessment: SHORT_TEXT,
  surveyThemes:         z.array(z.string().max(300)).max(8),
  trafficAssessment:    SHORT_TEXT,
  nextAction:           MEDIUM_TEXT,
});

export type ValidationInterpretation = z.infer<typeof ValidationInterpretationSchema>;

// ---------------------------------------------------------------------------
// Report — Step 2 Opus output (gated behind thresholds)
// ---------------------------------------------------------------------------

export const ConfirmedFeatureSchema = z.object({
  taskId:     z.string(),
  title:      z.string(),
  clicks:     z.number(),
  percentage: z.number(),
  evidence:   MEDIUM_TEXT,
});

export const RejectedFeatureSchema = z.object({
  taskId: z.string(),
  title:  z.string(),
  clicks: z.number(),
  reason: MEDIUM_TEXT,
});

/**
 * The committed build brief. `buildBrief` is always populated:
 *   - For 'strong' | 'moderate' | 'weak' → "Build X. Defer Y. Cut Z." style
 *   - For 'negative' → honest "do not build this because..." paragraph
 *
 * When signalStrength === 'negative', the following fields MUST also be
 * populated:
 *   - disconfirmedAssumptions: which specific assumptions from the original
 *     recommendation the market contradicted
 *   - pivotOptions: 2–3 adjacent paths the founder could try with the same
 *     belief state; empty array means "kill this direction, new discovery"
 *
 * For non-negative signals these fields are empty arrays.
 */
export const ValidationReportSchema = z.object({
  signalStrength:          z.enum(['strong', 'moderate', 'weak', 'negative']),
  confirmedFeatures:       z.array(ConfirmedFeatureSchema),
  rejectedFeatures:        z.array(RejectedFeatureSchema),
  surveyInsights:          LONG_TEXT,
  buildBrief:              LONG_TEXT,
  nextAction:              MEDIUM_TEXT,
  disconfirmedAssumptions: z.array(MEDIUM_TEXT).max(5).default([]),
  pivotOptions:            z.array(z.object({
    title:    SHORT_TEXT,
    rationale: MEDIUM_TEXT,
  })).max(3).default([]),
});

export type ConfirmedFeature = z.infer<typeof ConfirmedFeatureSchema>;
export type RejectedFeature  = z.infer<typeof RejectedFeatureSchema>;
export type ValidationReport = z.infer<typeof ValidationReportSchema>;
