"use client";

import { motion } from "framer-motion";
import { useState } from "react";
import { ChevronDown, HelpCircle, Search } from "lucide-react";
import Link from "next/link";
import LandingHeader from "@/components/LandingHeader";
import LandingFooter from "@/components/LandingFooter";

const fadeIn = {
  hidden: { opacity: 0, y: 20 },
  visible: { opacity: 1, y: 0, transition: { duration: 0.6 } },
};

const staggerContainer = {
  hidden: { opacity: 0 },
  visible: {
    opacity: 1,
    transition: {
      staggerChildren: 0.1,
      delayChildren: 0.1,
    },
  },
};

interface FAQItem {
  question: string;
  answer: string;
  category: string;
}

export default function FAQPage() {
  const [searchQuery, setSearchQuery] = useState<string>("");
  const [openIndex, setOpenIndex] = useState<number | null>(null);

  const faqData: FAQItem[] = [
    // Getting Started
    {
      category: "Getting Started",
      question: "What is NeuraLaunch?",
      answer:
        "NeuraLaunch is an AI-powered startup validation platform that combines intelligent blueprints with structured validation sprints. It helps founders transform ideas into validated, market-ready startups by providing AI-generated startup plans, 72-hour validation sprints, and a persistent AI co-founder that remembers your entire project history.",
    },
    {
      category: "Getting Started",
      question: "How do I get started?",
      answer:
        "Getting started is simple: 1) Sign in with your Google account, 2) Click 'Generate Your Blueprint' or 'New Chat', 3) Input your skills, passions, or initial idea, 4) Receive your AI-generated startup blueprint, and 5) Begin executing your validation sprint with AI assistance.",
    },
    {
      category: "Getting Started",
      question: "Do I need coding experience to use NeuraLaunch?",
      answer:
        "No! NeuraLaunch is designed for all founders, regardless of technical background. The platform guides you through startup validation before you write any code. The AI helps you understand market needs, customer profiles, and business models without requiring technical expertise.",
    },
    
    // Features
    {
      category: "Features",
      question: "What is an AI Blueprint?",
      answer:
        "An AI Blueprint is a comprehensive startup plan generated by Google Gemini AI. It includes market analysis, niche selection, competitive analysis, go-to-market strategy, revenue architecture, unit economics projections, and a structured validation plan. Think of it as having a Y Combinator partner create a detailed strategic roadmap for your startup.",
    },
    {
      category: "Features",
      question: "What is a 72-hour Validation Sprint?",
      answer:
        "The Validation Sprint is a structured, time-boxed framework for testing your core startup assumptions before building. Over 72 hours, you'll complete AI-assisted tasks like customer interviews, market research, competitive analysis, and landing page tests to validate real market demand. This prevents wasting months building something nobody wants.",
    },
    {
      category: "Features",
      question: "How does the AI Co-Founder work?",
      answer:
        "The AI Co-Founder uses RAG (Retrieval-Augmented Generation) technology with pgvector to remember your entire project history. Every conversation is saved and embedded in a vector database, allowing the AI to provide context-aware guidance based on all your previous discussions, decisions, and insights. It acts as a strategic partner that never forgets.",
    },
    {
      category: "Features",
      question: "What is the Landing Page Builder?",
      answer:
        "The Landing Page Builder creates professional landing pages from your blueprint to test market interest before building your product. It includes A/B testing capabilities, analytics tracking (views, signups, conversions), and smoke testing features to validate which features resonate most with your target audience.",
    },
    {
      category: "Features",
      question: "How does the gamification system work?",
      answer:
        "As you progress through your startup journey, you unlock achievements and earn points for completing validation tasks, conducting customer interviews, and reaching milestones. You can view global trends, see top-performing ideas on leaderboards, and discover patterns through the tag system. This keeps you motivated and engaged throughout the validation process.",
    },
    
    // AI & Technology
    {
      category: "AI & Technology",
      question: "Which AI models does NeuraLaunch use?",
      answer:
        "NeuraLaunch uses Google Gemini (gemini-1.5-flash and gemini-1.5-pro) as the primary AI for blueprint generation and strategic guidance. We also use OpenAI GPT-4 for MVP generation and OpenAI's text-embedding-3-small model for creating vector embeddings for the RAG system. The platform combines the strengths of multiple AI models for optimal results.",
    },
    {
      category: "AI & Technology",
      question: "What is RAG and why does it matter?",
      answer:
        "RAG (Retrieval-Augmented Generation) is a technology that gives the AI Co-Founder memory. Using PostgreSQL with pgvector extension, all your conversations are converted to vector embeddings and stored. When you ask questions, the AI retrieves relevant past conversations to provide context-aware responses. This means the AI understands your entire startup journey, not just the current conversation.",
    },
    {
      category: "AI & Technology",
      question: "How accurate is the AI-generated advice?",
      answer:
        "The AI provides strategic frameworks and guidance based on lean startup methodology and Y Combinator principles. While highly valuable, all AI suggestions should be validated with real customer research. The platform encourages you to test assumptions through the validation sprint, combining AI intelligence with real-world feedback for the best results.",
    },
    
    // Pricing & Access
    {
      category: "Pricing & Access",
      question: "Is NeuraLaunch free to use?",
      answer:
        "Please check our current pricing on the platform or contact our team. We're committed to making startup validation accessible to founders worldwide. Sign in to explore the features and see what's available to you.",
    },
    {
      category: "Pricing & Access",
      question: "Do I need to provide API keys?",
      answer:
        "No! All AI services are integrated and managed by NeuraLaunch. You don't need to sign up for Google Gemini, OpenAI, or any other service separately. Just sign in with Google and start validating your startup ideas immediately.",
    },
    
    // Data & Privacy
    {
      category: "Data & Privacy",
      question: "Is my data secure?",
      answer:
        "Yes! NeuraLaunch has an A+ security rating. We implement input validation with Zod schemas, rate limiting, XSS and CSRF protection, secure session management with NextAuth, and all data is stored in PostgreSQL with encryption. We never share your startup ideas or conversations with third parties.",
    },
    {
      category: "Data & Privacy",
      question: "Who owns the ideas and blueprints I generate?",
      answer:
        "You do! All ideas, blueprints, and content you generate through NeuraLaunch belong to you. We provide the tools and AI assistance, but your intellectual property remains yours. We don't claim any ownership over your startup ideas or business plans.",
    },
    {
      category: "Data & Privacy",
      question: "Can I delete my conversations and data?",
      answer:
        "Yes. You can delete individual conversations from the sidebar by clicking the delete icon that appears when you hover over a conversation. If you want to delete all your data, please contact our support team and we'll help you with account deletion.",
    },
    
    // Technical
    {
      category: "Technical",
      question: "What browsers are supported?",
      answer:
        "NeuraLaunch works best on modern browsers: Chrome, Firefox, Safari, and Edge (latest versions). We recommend using an up-to-date browser for the best experience with animations, real-time features, and AI interactions.",
    },
    {
      category: "Technical",
      question: "Can I use NeuraLaunch on mobile?",
      answer:
        "Yes! NeuraLaunch is fully responsive and works on mobile devices. However, for the best experience when working on detailed blueprints and validation sprints, we recommend using a tablet or desktop with a larger screen.",
    },
    {
      category: "Technical",
      question: "What if I encounter a bug or error?",
      answer:
        "If you encounter any issues, please use the Feedback button in the header to report it. Include as much detail as possible: what you were doing, what happened, and any error messages. You can also check our GitHub repository for known issues or open a new issue.",
    },
    
    // Support & Community
    {
      category: "Support & Community",
      question: "How can I get help or support?",
      answer:
        "You can get help through several channels: 1) Use the Feedback button in the header, 2) Check this FAQ page, 3) Visit our GitHub repository for documentation, 4) Open an issue on GitHub, or 5) Contact us through the contact form (link in footer).",
    },
    {
      category: "Support & Community",
      question: "Can I contribute to NeuraLaunch?",
      answer:
        "Absolutely! NeuraLaunch is open for contributions. Visit our GitHub repository at https://github.com/mansaraysaheedalpha/ideaspark to see the codebase, open issues, and contribution guidelines. We welcome bug fixes, feature additions, documentation improvements, and feedback from the community.",
    },
    {
      category: "Support & Community",
      question: "Where can I learn more or stay updated?",
      answer:
        "Follow our GitHub repository for updates, check the README for comprehensive documentation, and join our community discussions. We regularly update the platform with new features and improvements based on user feedback.",
    },
  ];

  const categories = Array.from(
    new Set(faqData.map((item) => item.category))
  );

  const filteredFAQs = faqData.filter(
    (item) =>
      item.question.toLowerCase().includes(searchQuery.toLowerCase()) ||
      item.answer.toLowerCase().includes(searchQuery.toLowerCase()) ||
      item.category.toLowerCase().includes(searchQuery.toLowerCase())
  );

  const toggleFAQ = (index: number) => {
    setOpenIndex(openIndex === index ? null : index);
  };

  return (
    <div className="pt-20 min-h-screen bg-background">
      <LandingHeader />
      
      {/* Hero Section */}
      <section className="relative overflow-hidden py-20 px-4 sm:px-6 lg:px-8 bg-gradient-to-b from-primary/5 via-background to-background">
        <motion.div
          initial="hidden"
          animate="visible"
          variants={staggerContainer}
          className="max-w-4xl mx-auto text-center"
        >
          <motion.div variants={fadeIn} className="mb-6">
            <div className="inline-flex items-center justify-center w-20 h-20 mb-6 bg-gradient-to-br from-primary to-secondary rounded-2xl">
              <HelpCircle className="w-10 h-10 text-primary-foreground" />
            </div>
          </motion.div>
          <motion.h1
            variants={fadeIn}
            className="text-5xl md:text-6xl font-black tracking-tight text-foreground mb-6"
          >
            Frequently Asked Questions
          </motion.h1>
          <motion.p
            variants={fadeIn}
            className="text-xl text-muted-foreground max-w-2xl mx-auto mb-8"
          >
            Find answers to common questions about NeuraLaunch, our features,
            and how to get the most out of the platform.
          </motion.p>

          {/* Search Bar */}
          <motion.div variants={fadeIn} className="max-w-2xl mx-auto">
            <div className="relative">
              <Search className="absolute left-4 top-1/2 -translate-y-1/2 w-5 h-5 text-muted-foreground" />
              <input
                type="text"
                placeholder="Search FAQs..."
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                className="w-full pl-12 pr-4 py-4 bg-card border border-border rounded-xl text-foreground placeholder:text-muted-foreground focus:outline-none focus:ring-2 focus:ring-primary focus:border-transparent"
              />
            </div>
          </motion.div>
        </motion.div>
      </section>

      {/* FAQ Content */}
      <section className="py-16 px-4 sm:px-6 lg:px-8">
        <div className="max-w-4xl mx-auto">
          {categories.map((category) => {
            const categoryFAQs = filteredFAQs.filter(
              (item) => item.category === category
            );
            
            if (categoryFAQs.length === 0) return null;

            return (
              <div key={category} className="mb-12">
                <h2 className="text-3xl font-bold text-foreground mb-6">
                  {category}
                </h2>
                <div className="space-y-4">
                  {categoryFAQs.map((item, index) => {
                    const globalIndex = faqData.indexOf(item);
                    const isOpen = openIndex === globalIndex;
                    
                    return (
                      <motion.div
                        key={globalIndex}
                        initial={{ opacity: 0, y: 10 }}
                        animate={{ opacity: 1, y: 0 }}
                        transition={{ delay: index * 0.05 }}
                        className="border border-border rounded-xl overflow-hidden bg-card"
                      >
                        <button
                          onClick={() => toggleFAQ(globalIndex)}
                          className="w-full px-6 py-5 flex items-center justify-between text-left hover:bg-muted/50 transition-colors"
                        >
                          <span className="text-lg font-semibold text-foreground pr-4">
                            {item.question}
                          </span>
                          <ChevronDown
                            className={`w-5 h-5 text-muted-foreground flex-shrink-0 transition-transform ${
                              isOpen ? "transform rotate-180" : ""
                            }`}
                          />
                        </button>
                        {isOpen && (
                          <motion.div
                            initial={{ height: 0, opacity: 0 }}
                            animate={{ height: "auto", opacity: 1 }}
                            exit={{ height: 0, opacity: 0 }}
                            transition={{ duration: 0.3 }}
                            className="px-6 pb-5"
                          >
                            <p className="text-muted-foreground leading-relaxed">
                              {item.answer}
                            </p>
                          </motion.div>
                        )}
                      </motion.div>
                    );
                  })}
                </div>
              </div>
            );
          })}

          {filteredFAQs.length === 0 && (
            <div className="text-center py-12">
              <p className="text-xl text-muted-foreground">
                No FAQs found matching your search. Try different keywords.
              </p>
            </div>
          )}
        </div>
      </section>

      {/* Still Have Questions Section */}
      <section className="py-16 px-4 sm:px-6 lg:px-8 bg-muted/30 dark:bg-slate-800/30">
        <div className="max-w-4xl mx-auto text-center">
          <motion.div
            initial="hidden"
            whileInView="visible"
            viewport={{ once: true }}
            variants={staggerContainer}
          >
            <motion.h2
              variants={fadeIn}
              className="text-4xl font-bold tracking-tight text-foreground mb-6"
            >
              Still Have Questions?
            </motion.h2>
            <motion.p
              variants={fadeIn}
              className="text-xl text-muted-foreground mb-8"
            >
              Can&apos;t find what you&apos;re looking for? We&apos;re here to help!
            </motion.p>
            <motion.div
              variants={fadeIn}
              className="flex flex-col sm:flex-row gap-4 justify-center"
            >
              <a
                href="https://forms.gle/WVLZzKtFYLvb7Xkg9"
                target="_blank"
                rel="noopener noreferrer"
                className="inline-flex items-center justify-center gap-2 px-6 py-3 bg-primary text-primary-foreground rounded-xl font-semibold hover:opacity-90 transition-opacity"
              >
                Send Feedback
              </a>
              <a
                href="https://github.com/mansaraysaheedalpha/ideaspark"
                target="_blank"
                rel="noopener noreferrer"
                className="inline-flex items-center justify-center gap-2 px-6 py-3 bg-card border border-border text-foreground rounded-xl font-semibold hover:bg-muted transition-colors"
              >
                View GitHub
              </a>
            </motion.div>
          </motion.div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="py-20 px-4 sm:px-6 lg:px-8">
        <div className="max-w-4xl mx-auto text-center">
          <motion.div
            initial="hidden"
            whileInView="visible"
            viewport={{ once: true }}
            variants={staggerContainer}
          >
            <motion.h2
              variants={fadeIn}
              className="text-4xl md:text-5xl font-bold tracking-tight text-foreground mb-6"
            >
              Ready to Get Started?
            </motion.h2>
            <motion.p
              variants={fadeIn}
              className="text-xl text-muted-foreground mb-10"
            >
              Start validating your startup idea with AI-powered precision.
            </motion.p>
            <motion.div variants={fadeIn}>
              <Link href="/generate">
                <motion.button
                  whileHover={{ scale: 1.05 }}
                  whileTap={{ scale: 0.95 }}
                  className="inline-flex items-center gap-2 px-8 py-4 bg-gradient-to-r from-primary to-secondary text-primary-foreground rounded-xl font-semibold text-lg shadow-lg hover:shadow-xl transition-all"
                >
                  Generate Your Blueprint
                </motion.button>
              </Link>
            </motion.div>
          </motion.div>
        </div>
      </section>

      <LandingFooter />
    </div>
  );
}
